// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isPlaceholder => false;
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSB2ub2hSBSPFEyJ2hy06JQo1whm6R2g',
    appId: '1:335880283840:web:efacd14b5d6c6638576f25',
    messagingSenderId: '335880283840',
    projectId: 'civic-ping-pk',
    authDomain: 'civic-ping-pk.firebaseapp.com',
    storageBucket: 'civic-ping-pk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWw2HXYpSavls6eHctA8AMT3vBeSAE2bQ',
    appId: '1:335880283840:android:5a9c251e4553e0e6576f25',
    messagingSenderId: '335880283840',
    projectId: 'civic-ping-pk',
    storageBucket: 'civic-ping-pk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSB2ub2hSBSPFEyJ2hy06JQo1whm6R2g',
    appId: '1:335880283840:web:7c7b78b81029599a576f25',
    messagingSenderId: '335880283840',
    projectId: 'civic-ping-pk',
    authDomain: 'civic-ping-pk.firebaseapp.com',
    storageBucket: 'civic-ping-pk.firebasestorage.app',
  );
}
